# Generated by Django 5.0.14 on 2025-12-23 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='구분 (대분류)')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '구분 마스터',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='분류 (소분류)')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dashboard.categorygroup', verbose_name='구분')),
            ],
            options={
                'verbose_name': '분류 마스터',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='항목')),
                ('unit', models.CharField(max_length=50, verbose_name='단위')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='dashboard.category', verbose_name='분류')),
            ],
            options={
                'verbose_name': '지표 항목 마스터',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='실적 일자')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='일실적')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='dashboard.indicator', verbose_name='지표 항목')),
            ],
            options={
                'verbose_name': '일일 지표 실적',
                'ordering': ['-date', 'indicator'],
                'unique_together': {('indicator', 'date')},
            },
        ),
    ]
