# Generated by Django 5.0.14 on 2025-12-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='code',
            field=models.CharField(default='00', max_length=2, verbose_name='사업영역 코드 (2자리)'),
        ),
    ]
