# Generated by Django 5.0.14 on 2025-12-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_categorygroup_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='메뉴 코드')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴 명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('authorized_users', models.ManyToManyField(blank=True, related_name='permitted_menus', to=settings.AUTH_USER_MODEL, verbose_name='권한 부여 사용자')),
                ('category_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='dashboard.categorygroup', verbose_name='연결된 사업영역')),
            ],
            options={
                'verbose_name': '메뉴 마스터',
                'ordering': ['order', 'name'],
            },
        ),
    ]
