# Generated by Django 5.0.14 on 2025-12-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category_group',
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='code',
            field=models.CharField(default='00', max_length=2, unique=True, verbose_name='사업영역 코드 (2자리)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='dashboard.categorygroup', to_field='code', verbose_name='메뉴 코드'),
        ),
    ]
