# Generated by Django 5.0.14 on 2025-12-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_menu_category_group_alter_categorygroup_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(default='00', max_length=2, unique=True, verbose_name='사업영역 코드 (2자리)'),
        ),
    ]
