# Generated by Django 5.0.14 on 2025-12-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_menu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='code',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu', to_field='code'),
        ),
    ]
