# Generated by Django 5.0.14 on 2025-12-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_categorygroup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='지표코드'),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='code',
            field=models.CharField(default='00', max_length=2, verbose_name='사업영역 코드 (2자리)'),
        ),
    ]
