# Generated by Django 5.0.14 on 2025-12-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_indicator_code_alter_categorygroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='code',
            field=models.CharField(default='00', max_length=2, verbose_name='사업영역 코드 (2자리)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(default='00', max_length=2, unique=True, verbose_name='메뉴코드'),
        ),
    ]
