# Generated by Django 5.0.14 on 2025-12-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_categorygroup_code_alter_menu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyperformance',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='일실적'),
        ),
    ]
